name: i18n-ai-translate

on:
    pull_request:
        # Only trigger when en.json has been modified
        paths:
            - "custom_components/fritzbox_callmonitor_raw/translations/en.json"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: i18n-ai-translate
              uses: taahamahdi/i18n-ai-translate@master
              with:
                  json-file-path: custom_components/fritzbox_callmonitor_raw/translations/en.json
                  api-key: ${{ secrets.OPENAI_API_KEY }}
